DOMAIN = "dtek_shutdowns"
CONF_REGION = "region"
CONF_GROUP = "group"
CONF_CITY = "city"
CONF_STREET = "street"
CONF_HOUSE = "house_number"
CONF_AGENT_URL = "agent_url"
CONF_GROUP_BY_ADDRESS = "by_address"
GROUP_LIST = [f"{q}.{s}" for q in [*range(1, 61), *range(1001, 1007)] for s in (1, 2)]